#!/bin/sh -e

# Enable serial console
systemctl enable "serial-getty@ttyGS0.service"

# Enable wpa-supplicant (for wifi)
systemctl enable wpa_supplicant
systemctl enable wpa_supplicant@wlan0

# Make sure we have the "gpio" group
groupadd --force --system gpio
usermod --append --groups gpio ubuntu

# Prepare the system for booting
update-rpi-boot || true
