#!/bin/sh -e

# Enable serial console
systemctl enable "serial-getty@ttyS0.service"

# Make sure we have the "gpio" group
groupadd --force --system gpio
usermod --append --groups gpio ubuntu

# Prepare the system for booting
update-rpi-boot || true
