#!/bin/bash

# Check we are root
if test "$(id -u)" -ne 0 ; then
	echo "${0}: can only be run as root"
	exit 1
fi

# Run the scripts one by one
echo '*** Running Minimal OS initial setup'
run-parts "/lib/minimal-os-setup.d"

# Make sure we the setup service is disabled
systemctl disable minimal-os-setup.service 2> /dev/null

# We run the service only once (normally) so we mask it. Other packages
# needing to run setup enable it in their "postinst" script. Masking makes
# sure that package updates won't accidentally re-enable the script.
systemctl mask minimal-os-setup.service 2> /dev/null
