#!/bin/sh
set -e

# Fix the NTP server to AWS' own EC2 NTP server
sed -i -E 's|^#?NTP=.*$|NTP=169.254.169.123|g' /etc/systemd/timesyncd.conf

# Mask/disable TTYs on console and enable serial
systemctl enable "serial-getty@ttyS0.service"
systemctl disable "getty@tty1.service"
systemctl mask "getty@tty1.service"

# Install GRUB on the boot device
BOOT_DEVICE="/dev/$(findmnt -no SOURCE / | xargs lsblk -no PKNAME)"
GRUB_ARCH="$(uname -m | sed 's|aarch64|arm64|g')-efi"

grub-install --target="${GRUB_ARCH}" "${BOOT_DEVICE}"
update-grub

 # Enable "minimal-os-setup" to run on first boot
systemctl enable minimal-os-setup 2> /dev/null || true
