#!/bin/bash

# Update locale if unset in /etc/default/locale
grep -q '^LANGUAGE' '/etc/default/locale' || {
	/usr/sbin/locale-gen en_US.UTF-8
	echo 'Setting default locale to en_US.UTF-8'
	/usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANGUAGE=en_US
}

# Disable "bracketed paste"
grep -q 'enable-bracketed-paste' '/etc/inputrc' || {
	echo '' >> '/etc/inputrc'
	echo '# Disable "bracketed paste"' >> '/etc/inputrc'
	echo 'set enable-bracketed-paste off' >> '/etc/inputrc'
}
