#!/bin/bash

# Update locale if unset in /etc/default/locale
grep -q '^LANGUAGE' '/etc/default/locale' || {
	/usr/sbin/locale-gen en_US.UTF-8
	echo 'Setting default locale to en_US.UTF-8'
	/usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LANGUAGE=en_US
}

# Add the 'systemd-timesync' user if not already there
id systemd-timesync > /dev/null 2>&1 || {
	echo 'Adding "systemd-timesync" system user'
	adduser --system --group --no-create-home --home /run/systemd/timesync \
		--gecos "systemd Timesync" systemd-timesync
}
