#!/bin/sh -e
. /usr/share/minimal-os-setup/common-functions

# Make sure SSH has all the keys
_notice 'Generating SSH host keys'

_create_host_key() {
	if test -f "${1}"
	then
		_notice "SSH host key file '${1}' exists, skipping..."
	else
		_notice "Generating SSH host key file '${1}', this may take some time ..."
		ssh-keygen -f "${1}" -N '' -C "$(hostname)" -t "${2}"
	fi
}

_create_host_key /etc/ssh/ssh_host_rsa_key rsa
_create_host_key /etc/ssh/ssh_host_ecdsa_key ecdsa
_create_host_key /etc/ssh/ssh_host_ed25519_key ed25519
