#!/bin/sh
. /usr/share/minimal-os-setup/common-functions

# Run the scripts one by one
_notice 'Starting'
run-parts "/lib/minimal-os-setup.d"
_notice 'Done'

# Make sure we the setup service is disabled
systemctl disable minimal-os-setup.service 2> /dev/null || true

# We run the service only once (normally) so we mask it. Other packages
# needing to run setup enable it in their "postinst" script. Masking makes
# sure that package updates won't accidentally re-enable the script.
systemctl mask minimal-os-setup.service 2> /dev/null || true
