#!/bin/bash

# Check we are root
if test "$(id -u)" -ne 0 ; then
	echo "${0}: can only be run as root"
	exit 1
fi

# Simply calling `dpkg-reconfigure` will regenenerate any missing key
dpkg-reconfigure openssh-server
