#!/bin/sh
set -e

# Check we are root
if test "$(id -u)" -ne 0 ; then
	echo "${0}: can only be run as root"
	exit 1
fi

# Print a message both to stderr and console
_notice() {
	NAME="$(basename $(realpath "${0}"))"
	printf 'Setup [%s] %s\n' "${NAME}" "${*}"
	printf '\033[0m[\033[36mNOTICE\033[0m] Setup [%s] \033[1;37m%s\033[0m\n' \
		"${NAME}" "${*}" > /dev/console
}

# Attempt to grow the partition
_grow_root_partition() {
	lsblk -no "name,pkname" "$(findmnt -no SOURCE /)" | {
		read PART_DEV DISK_DEV
		_notice "Growing '/dev/${PART_DEV}' root partition."

		# Find the old size (for messages)
		OLD_SIZE=$(lsblk -no SIZE "/dev/${PART_DEV}")

		# Find the partition number from our device
		PART_NUM="$(cat /sys/class/block/${PART_DEV}/partition)"

		# Resize the partition to 100% of the available size and reload
		parted ---pretend-input-tty "/dev/${DISK_DEV}" <<- EOF
			resizepart 2 100%
			yes
			quit
			EOF

		# parted -s  resizepart "${PART_NUM}" "100%"
		partprobe "/dev/${DISK_DEV}"

		# Resize the filesystem to the new partition size
		resize2fs "/dev/${PART_DEV}"

		# Find the new size and show what changed
		NEW_SIZE=$(lsblk -no SIZE "/dev/${PART_DEV}")
		_notice "Partition '/dev/${PART_DEV}' grown from ${OLD_SIZE} to ${NEW_SIZE}"
	}
}

# Set hostname (defaults to "ubuntu")
_set_hostname() {
	NAME="${1:-ubuntu}"
	_notice "Setting hostname to '${NAME}'"

	# Set the hostname in "/etc/hostname"
	echo "${NAME}" > "/etc/hostname"

	# Setup a very basic "/etc/hosts" file
	cat > "/etc/hosts" <<- EOF
		127.0.0.1	localhost
		127.0.1.1	${NAME}	${NAME}.local
	EOF

	# Remember this host name in this session
	hostname "${NAME}"
}
