#!/bin/sh
set -e

# Check we are root
if test "$(id -u)" -ne 0 ; then
	echo "${0}: can only be run as root"
	exit 1
fi

# Print a message both to stderr and console
_notice() {
	NAME="$(basename $(realpath "${0}"))"
	printf 'Setup [%s] %s\n' "${NAME}" "${*}"
	printf '\033[0m[\033[36mNOTICE\033[0m] Setup [%s] \033[1;37m%s\033[0m\n' \
		"${NAME}" "${*}" > /dev/console
}
