name: Release Packages

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Package

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Packages
        run: make all

      - name: Build Repository
        run: |
          apt-get install --yes gpgv1
          echo "${{ secrets.GPG_KEY }}" | gpg1 --import
