name: Release Packages

on:
  workflow_dispatch:

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Githb Pages
        uses: actions/configure-pages@v5

      - name: Build Packages
        run: make all

      - name: Build Repository
        run: |
          sudo apt-get install --yes gnupg1
          echo "${{ secrets.GPG_KEY }}" | gpg1 --quiet --batch --import
          make repo
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo

      - name: Deploy Pages
        uses: actions/deploy-pages@v4

      - name: Create Release
        run: |
          RELEASE=$(date +'%Y%m%d.%H%M%S')
          gh release create "${RELEASE}" --title "${RELEASE}" --notes '' *.deb
        env:
          GH_TOKEN: ${{ github.token }}
