name: Release Packages

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Package

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Packages
        run: make all

      - name: Build Repository
        run: |
          sudo apt-get install --yes gnupg1
          echo "${{ secrets.GPG_KEY }}" | gpg1 --import
          make repo
        env:
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
